# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FrameContainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fc_id', models.DecimalField(db_index=True, decimal_places=0, max_digits=32)),
                ('fc_path', models.TextField()),
                ('video_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_name', models.TextField(primary_key=True, serialize=False)),
                ('video_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='fc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.FrameContainer'),
        ),
    ]
